#!/bin/bash -ex

dl() {
    [[ "$FAB_HTTP_PROXY" ]] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd "$2"; curl -L -f -O $PROXY "$1"; cd -
}

get_html_tags() {
    local IFS='>'
    read -d '<' TAG VALUE
}

TMP_DIR="$(mktemp -d /tmp/redmine.XXXXX)"
RELEASE="redmine-$(gh_releases redmine/redmine | sort -V | tail -1).tar.gz"

SRC="/usr/local/src"
dl "https://www.redmine.org/releases/$RELEASE" "$SRC"
dl "https://www.redmine.org/releases/$RELEASE.sha256" "$SRC"

cd "$SRC"
shasum -c "$RELEASE.sha256"
rm "$RELEASE.sha256"
