#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION=4.0.3
SRC="/usr/local/src"
dl http://www.redmine.org/releases/redmine-${VERSION}.tar.gz $SRC
dl http://www.redmine.org/releases/redmine-${VERSION}.tar.gz.md5 $SRC

cd $SRC
md5sum -c redmine-${VERSION}.tar.gz.md5
rm redmine-${VERSION}.tar.gz.md5

