#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"
dl http://rubyforge.org/frs/download.php/76771/redmine-2.2.3.tar.gz $SRC
dl http://rubyforge.org/frs/download.php/76772/redmine-2.2.3.tar.gz.md5 $SRC

cd $SRC
md5sum -c redmine-2.2.3.tar.gz.md5
rm redmine-2.2.3.tar.gz.md5

