#!/bin/sh -ex

ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/redmine

# start mysql
/etc/init.d/mysql start

# install redmine and configure it
tar -zxf $SRC/redmine-*.tar.gz -C $(dirname $WEBROOT)
rm -rf $SRC/redmine-*.tar.gz

mv $WEBROOT $WEBROOT.orig
mv $(dirname $WEBROOT)/redmine-* $WEBROOT
cp $WEBROOT.orig/config/database.yml $WEBROOT/config/database.yml
sed -i "s|mysql2|mysql|" $WEBROOT/config/database.yml
rm -rf $WEBROOT.orig

CONF=$WEBROOT/db/migrate/001_setup.rb
SHA1_PASS=$(echo -n $ADMIN_PASS | sha1sum | cut -d " " -f 1)
sed -i "s/:hashed_password \(.*\)/:hashed_password => \"$SHA1_PASS\",/" $CONF

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
cd $WEBROOT
bundle --without=rmagick install
rake generate_secret_token
rake db:migrate RAILS_ENV="production"
REDMINE_LANG=en rake redmine:load_default_data RAILS_ENV="production"
unset HTTP_PROXY

project_init() {
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE redmine_production;
INSERT projects (id, name, is_public, created_on, updated_on, identifier, status, lft, rgt)
VALUES ($1, '$2-helloworld', '1', '2012-01-01 13:00:00', '2012-01-01 13:00:00', '$2-helloworld', '1', '1', '2');
EOF

mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE redmine_production;
INSERT repositories (id, project_id, url, root_url, type, path_encoding, log_encoding, identifier, is_default)
VALUES ($1, '$1', '$4', '$4', '$3', 'UTF8', 'UTF-8', '$2-helloworld', '1');
EOF

names="issue_tracking time_tracking news documents files wiki repository boards"
for name in $names; do
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE redmine_production;
INSERT enabled_modules (id, project_id, name) VALUES (NULL, '$1', '$name');
EOF
done

for tracker_id in 1 2 3; do
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE redmine_production;
INSERT projects_trackers (project_id, tracker_id) VALUES ('$1', '$tracker_id');
EOF
done
}

# configure projects and repositories
project_init 1 git Repository::Git        /var/cache/git/helloworld.git
project_init 2 bzr Repository::Bazaar     /srv/repos/bzr/helloworld
project_init 3 hg  Repository::Mercurial  /srv/repos/hg/helloworld
project_init 4 svn Repository::Subversion file:///srv/repos/svn/helloworld

# create welcome message
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
USE redmine_production;
INSERT settings (id, name, value) VALUES 
(1, 'welcome_text', 'h2. Getting started

* Log in as *admin* and start managing your projects
* "TurnKey Linux Redmine appliance release notes":http://www.turnkeylinux.org/redmine
* Redmine resources ("Guide":http://www.redmine.org/guide, "Forums":http://www.redmine.org/projects/redmine/boards, "FAQ":http://www.redmine.org/wiki/redmine/FAQ)
');
EOF

# configure outgoing email
cat >$WEBROOT/config/configuration.yml<<EOF
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "localhost"
      port: 25
EOF

# turnkey-credit (passenger substitute x2 bug)
cat >>$WEBROOT/public/stylesheets/application.css<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
#turnkey-credit a:hover {
    text-decoration: underline;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='http://www.turnkeylinux.org/redmine'>Redmine Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=$WEBROOT/app/views/layouts/base.html.erb
sed -i "s|</body>|$TURNKEY_CREDIT\n</body>|" $FOOTER

# configure permissions
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data $WEBROOT/files

# stop mysql
/etc/init.d/mysql stop

