#!/bin/bash -e
# change the password redmine uses for DB access

. /etc/default/inithooks

PASSWORD=$(mcookie)

sed -i "s|\\(RedmineDbPass\\) .*|\1 \"$PASSWORD\"|g" /etc/apache2/conf-available/redmine_webaccess.conf
sed -i "s|\\(password:\\) .*|\1 $PASSWORD|g" /var/www/redmine/config/database.yml

$INITHOOKS_PATH/bin/mysqlconf.py --user=redmine --pass="$PASSWORD"

/etc/init.d/apache2 restart
