#!/bin/bash -e
# change the password redmine uses for DB access

. /etc/default/inithooks

PASSWORD=$(mcookie)
WEBROOT=/var/www/redmine

sed -i "s|\\(RedmineDbPass\\) .*|\1 \"$PASSWORD\"|g" /etc/apache2/conf-available/redmine_webaccess.conf
sed -i "s|\\(password:\\) .*|\1 $PASSWORD|g" $WEBROOT/config/database.yml
sed -i "s|RedmineApp::Application.config.secret_key_base = .*|RedmineApp::Application.config.secret_key_base = '$(mcookie)$(mcookie)$(mcookie)$(mcookie)'|g" $WEBROOT/config/initializers/secret_token.rb

$INITHOOKS_PATH/bin/mysqlconf.py --user=redmine --pass="$PASSWORD"

/etc/init.d/apache2 restart
