#!/bin/bash -e
# change the password redmine uses for DB access

. /etc/default/inithooks

gen_pass() {
    unset USER PASSWORD
    USER="$1"
    PASSWORD=$(mcookie)$(mcookie)
    $INITHOOKS_PATH/bin/mysqlconf.py --user="$USER" --pass="$PASSWORD"
    echo "$PASSWORD"
fi

WEBROOT=/var/www/redmine
SECRET=$(mcookie)$(mcookie)$(mcookie)$(mcookie)

# regenerate redmine DB user password & set secret
PASSWORD=$(gen_pass redmine)
sed -i "s|\\(RedmineDbPass\\) .*|\1 \"$PASSWORD\"|g" /etc/apache2/conf-available/redmine_webaccess.conf
sed -i "s|\\(password:\\) .*|\1 $PASSWORD|g" $WEBROOT/config/database.yml
sed -i "s|RedmineApp::Application.config.secret_key_base = .*|RedmineApp::Application.config.secret_key_base = '$SECRET)'|g" $WEBROOT/config/initializers/secret_token.rb

# regenerate mariadb_admin password (for Webmin MariaDB module)
PASSWORD=$(gen_pass mariadb_admin)
sed -i "\|^pass=|s|=.*|=$PASSWORD|" /etc/webmin/mysql/config

systemctl restart apache2
