#!/bin/bash -e
# set redmine admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
printf '%s\n' "$APP_PASS" | \
    $INITHOOKS_PATH/bin/redmine.py --pass-stdin --email="$APP_EMAIL"
